//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysch_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_details
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Address { get; set; }
        public string Class { get; set; }
        public string Sponsor { get; set; }
    }
}
